spring.application.name=spring-homework-002
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/hw002
spring.datasource.username=postgres
spring.datasource.password=********

